insert into ADMIN.USERS (user_role, name, surname, patronymic, password, birthday, PHONE_NUMBER, EMAIL)
values ('ADMIN', 'Dima', 'Okylich', 'Iur`evich', 'pravoda01', '16.04.2004', '+80297080318', 'dima123.zample@gmail.com');

CALL ADMIN.REGISTRATION_NEW_USER('ADMIN', 'ADMIN',
                                  'ADMIN_SUR', 'ADMIN_PAT',
                                 'ADMIN', '16.04.2004',
                                    '+375297080318', 'dima123.zample@gmail.com');

CALL ADMIN.INSERT_NEW_DISEASE('Альц ГЕЙМЕР', '');
CALL ADMIN.INSERT_NEW_DISEASE('Альц ГЕЙМЕР 1', '');
CALL ADMIN.INSERT_NEW_DISEASE('Альц ГЕЙМЕР 2', '');

CALL ADMIN.INSERT_NEW_SYMPTOM('DOTA', '');
CALL ADMIN.INSERT_NEW_SYMPTOM('CS2', '');
CALL ADMIN.INSERT_NEW_SYMPTOM('TARKOW', '');

CALL ADMIN.DISEASES_TO_SYMPTOMS(1, 2);
CALL ADMIN.DISEASES_TO_SYMPTOMS(1, 3);

CALL ADMIN.DISEASES_TO_SYMPTOMS(2, 2);
CALL ADMIN.DISEASES_TO_SYMPTOMS(2, 4);

CALL ADMIN.DISEASES_TO_SYMPTOMS(3, 3);
CALL ADMIN.DISEASES_TO_SYMPTOMS(3, 4);

DELETE FROM ADMIN.USERS;

DELETE FROM ADMIN.DISEASESTOSYMPTOMS where ID = 7;

commit;

DELETE FROM ADMIN.DIAGNOSES;

commit;

select * from ADMIN.USERS;
select * from ADMIN.APPOINTMENTS;
select * from ADMIN.DISEASES;
select * from ADMIN.SYMPTOMS;
select * from ADMIN.DISEASESTOSYMPTOMS;
select * from ADMIN.DIAGNOSES;

SELECT * FROM ADMIN.SYMPTOMS SYMP
         WHERE (SELECT COUNT(*) FROM DISEASESTOSYMPTOMS WHERE DISEASESTOSYMPTOMS.DISEASE_ID = 1 AND DISEASESTOSYMPTOMS.SYMPTOM_ID = SYMP.SYMPTOM_ID) != 0;

SELECT COUNT(*) FROM ADMIN.USERS;

DELETE FROM APPOINTMENTS;

commit;

insert into DISEASES(NAME, DESCRIPTION) values ('Test', 'AAAAAAA');

CALL ADMIN.DEBUG_GET_ALL_USERS();
CALL ADMIN.GET_CURRENT_USER_DEBUG();

SELECT * FROM DEBUG_LOG;

SELECT * FROM USERS;

SELECT * FROM all_objects WHERE object_name = 'DBMS_CRYPTO' AND object_type = 'PACKAGE';
