grant RESTRICTED SESSION to ADMIN;

grant execute ON DBMS_CRYPTO TO ADMIN;

CREATE ROLE DOCTOR_RL;

GRANT CREATE SESSION, RESTRICTED SESSION TO DOCTOR_RL;

GRANT EXECUTE ON ADMIN.APPOINTMENT_PACK TO DOCTOR_RL;
GRANT EXECUTE ON ADMIN.DIAGNOSE_PACK TO DOCTOR_RL;
GRANT EXECUTE ON ADMIN.DISEASE_PACK TO DOCTOR_RL;
GRANT EXECUTE ON ADMIN.USER_PACK TO DOCTOR_RL;
GRANT EXECUTE ON ADMIN.MEDICINE_PACK TO DOCTOR_RL;
GRANT EXECUTE ON ADMIN.SYMPTOM_PACK TO DOCTOR_RL;
GRANT EXECUTE ON ADMIN.MTM_PACK TO DOCTOR_RL;

CREATE ROLE PATIENT_RL;

GRANT CREATE SESSION, RESTRICTED SESSION TO PATIENT_RL;

GRANT EXECUTE ON ADMIN.APPOINTMENT_PACK TO PATIENT_RL;
GRANT EXECUTE ON ADMIN.DIAGNOSE_PACK TO PATIENT_RL;
GRANT EXECUTE ON ADMIN.DISEASE_PACK TO PATIENT_RL;
GRANT EXECUTE ON ADMIN.USER_PACK TO PATIENT_RL;
GRANT EXECUTE ON ADMIN.MEDICINE_PACK TO PATIENT_RL;
GRANT EXECUTE ON ADMIN.SYMPTOM_PACK TO PATIENT_RL;
GRANT EXECUTE ON ADMIN.MTM_PACK TO PATIENT_RL;

CREATE ROLE LOGREG_RL;

GRANT CREATE SESSION, RESTRICTED SESSION TO LOGREG_RL;

GRANT EXECUTE ON ADMIN.USER_PACK TO LOGREG_RL;

-- DELETE

--DROP ROLE ADMIN_RL;
DROP ROLE DOCTOR_RL;
DROP ROLE PATIENT_RL;
DROP ROLE LOGREG_RL;

