CREATE OR REPLACE TRIGGER DELETE_USER_LINKS_TRIGGER
BEFORE DELETE
ON ADMIN.USERS
FOR EACH ROW
BEGIN
    DELETE FROM ADMIN.APPOINTMENTS
           WHERE ADMIN.APPOINTMENTS.PATIENT_ID = :OLD.USER_ID OR ADMIN.APPOINTMENTS.DOCTOR_ID = :OLD.USER_ID;

    DELETE FROM ADMIN.DIAGNOSES
           WHERE ADMIN.DIAGNOSES.PATIENT_ID = :OLD.USER_ID OR ADMIN.DIAGNOSES.DOCTOR_ID = :OLD.USER_ID;
end;

DROP TRIGGER DELETE_USER_LINKS_TRIGGER;