CREATE OR REPLACE TRIGGER DELETE_USER_LINKS_TRIGGER
BEFORE DELETE
ON ADMIN.USERS
FOR EACH ROW
BEGIN
    DELETE FROM ADMIN.APPOINTMENTS
           WHERE ADMIN.APPOINTMENTS.PATIENT_ID = :OLD.USER_ID OR ADMIN.APPOINTMENTS.DOCTOR_ID = :OLD.USER_ID;

    DELETE FROM ADMIN.DIAGNOSES
           WHERE ADMIN.DIAGNOSES.PATIENT_ID = :OLD.USER_ID OR ADMIN.DIAGNOSES.DOCTOR_ID = :OLD.USER_ID;
end;

CREATE OR REPLACE TRIGGER DELETE_DIAGNOSE_LINKS_TRIGGER
BEFORE DELETE
ON ADMIN.DIAGNOSES
FOR EACH ROW
BEGIN
    DELETE FROM ADMIN.DIAGNOSESTOSYMPTOMS
           WHERE ADMIN.DIAGNOSESTOSYMPTOMS.DIAGNOSE_ID = :OLD.DIAGNOSE_ID;

    DELETE FROM ADMIN.DIAGNOSESTOMEDICINES
           WHERE ADMIN.DIAGNOSESTOMEDICINES.DIAGNOSE_ID = :OLD.DIAGNOSE_ID;
end;

CREATE OR REPLACE TRIGGER DELETE_SYMPTOM_LINKS_TRIGGER
BEFORE DELETE
ON ADMIN.SYMPTOMS
FOR EACH ROW
BEGIN
    DELETE FROM ADMIN.DIAGNOSESTOSYMPTOMS
           WHERE ADMIN.DIAGNOSESTOSYMPTOMS.SYMPTOM_ID = :OLD.SYMPTOM_ID;

    DELETE FROM ADMIN.DISEASESTOSYMPTOMS
           WHERE ADMIN.DISEASESTOSYMPTOMS.SYMPTOM_ID = :OLD.SYMPTOM_ID;
end;

CREATE OR REPLACE TRIGGER DELETE_DISEASE_LINKS_TRIGGER
BEFORE DELETE
ON ADMIN.DISEASES
FOR EACH ROW
BEGIN
    DELETE FROM ADMIN.DISEASESTOSYMPTOMS
           WHERE ADMIN.DISEASESTOSYMPTOMS.DISEASE_ID = :OLD.DISEASE_ID;
end;

DROP TRIGGER DELETE_USER_LINKS_TRIGGER;
DROP TRIGGER DELETE_DIAGNOSE_LINKS_TRIGGER;
DROP TRIGGER DELETE_DISEASE_LINKS_TRIGGER;
DROP TRIGGER DELETE_SYMPTOM_LINKS_TRIGGER;
