-- ДЛЯ АДМИНА

ALTER USER ADMIN QUOTA 5M on MEDKIT_TS;

ALTER USER ADMIN DEFAULT TABLESPACE MEDKIT_TS;
ALTER USER ADMIN TEMPORARY TABLESPACE MEDKIT_TEMP_TS;

-- ДЛЯ ВРАЧЕЙ

create profile DOCTOR_PF limit
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 12
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 60;

CREATE USER DOCTOR IDENTIFIED BY "DOC"
    default tablespace MEDKIT_TS
    temporary tablespace MEDKIT_TEMP_TS
    profile DOCTOR_PF
    quota 16M on MEDKIT_TS;

grant create session to DOCTOR;

grant SYSDBA to DOCTOR;

DROP USER DOCTOR CASCADE;